config/routes.rb
Devolve::Application.routes.draw do
  get "communities/create"

  get "communities/index"
  
  get "communities/delete"
  
  get "communities/join"
  get "friendship/index"
  get "communities/newpost"
  
  get "communities/newcomment"
  get "communities/destroy"
  get "communities/save"
  get "communities/show"
  get "communities/post"

  get "mailbox/show"
 get "mailbox/trash"
  get "messages/show"
get "messages/destroy"
get "messages/undelete"
get "messages/delete_from_trash"
  get "sent/index"

  get "sent/show"

  get "sent/new"
  get "sent/delete"
  
  get "sent/new_reply"
  get "messages/forward"

    resources :events
  get "search/index"

  get "codes/index"

  get "calendar/index"
get 'users/invitation'

get 'events/new'
  get "codes/create"
  get 'communities/create_post'
  get "codes/save"

  get "bookmarks/index"

  get "bookmarks/create"
  get "bookmarks/saved"
  
  get "bookmarks/notsaved"
  get "messages/reply"
 match 'mailbox/inbox' => 'mailbox#index'
 
 match 'communities/create_post'=>'communities#create_post'
  resources :microposts, :only => [:create, :destroy]
  resources :bookmarks,:only=>[:create,:destroy]
  
  resources :codes,:only=>[:create,:destroy]
  get "profiles/show"

  get "profiles/edit"
  get "microposts/destroy"
  get "bookmarks/destroy"
  
 get "home/gettingstarted"
  get "profile/show"
  match 'home/create' => 'home#create'
  match 'communities/save' => 'communities#save'
  match 'profiles/create' => 'profiles#create'
  
  match 'friendship/create' => 'friendship#create'
  
  match 'friendship/accept' => 'friendship#accept'
  
  match 'friendship/decline' => 'friendship#decline'
  
  match 'friendship/cancel' => 'friendship#cancel'

match 'microposts'=>'microposts/create'
match 'microposts/destroy'=>'microposts#destroy'

match 'bookmarks/destroy'=>'bookmarks#destroy'
match 'codes/destroy'=>'codes#destroy'
  resources :profiles,:commus,:sent,:messages,:mailbox,:member =>{ :reply => :get,:forward => :get, :undelete => :put  },:collection => { :trash => :get }
 

 get "home/getting_started_completed"
  devise_for :users
  get "home/index"
  get "home/create"
  match 'bookmarks/save' => 'bookmarks#save'
  
  match 'codes/save' => 'codes#save'
  get "home/help"

  match 'profiles/:id' => 'profile#show'
  match 'bookmarks/:id' => 'bookmarks#index'
  
  match 'communities/:id' => 'communities#show'
  
  match 'codes/:id' => 'codes#index'
    match 'codes/:id1/:id' => 'codes#view'

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
    
end

app/views/shared/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="errorExplanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %> 


<table class="microposts" summary="User microposts" width="510px">
<%= render :partial => 'shared/feed_item', :collection => @feed_items %>

 </table> <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr> <td class="gravatar">
<td class="micropost"> <span class="user">

	<%= image_tag feed_item.user.profile.image_url.to_s,:width=>40%>
<h3 id="micropostname"><%= link_to feed_item.user.profile.name, profile_path(feed_item.user.id) %></h3>
	
<span class="content" id="micropostdisplaycontent"><%= feed_item.content %></span> <span class="timestamp"><h6 id="micropostposted">
Posted <%= time_ago_in_words(feed_item.created_at) %> ago.  </h6></span>
</td> 

<% if @user.id==feed_item.user.id %> <td id="micropost_delete">
	

	<%= link_to "delete",micropost_url(feed_item.id),:id => feed_item.id,:method=>:delete,:confirm => "You sure?" %> 
	</td> 
	
	<% end %> </tr>

app/views/shared/_micropost_form.html.erb
<%= form_for :micropost,:url =>{:controller=>'microposts',:action=> 'create'} do |f| %>

	
<%= render 'shared/error_messages', :object => @micropost %>

 <div class="field">
<%= f.text_area :content,:maxlength=>"140",
:onkeyup=>"CheckFieldLength(micropost_content, 'charcount', 'remaining', 140);",:onkeydown=>"CheckFieldLength(micropost_content, 'charcount', 'remaining', 140);", :onmouseout=>"CheckFieldLength(micropost_content, 'charcount', 'remaining', 140);",:placeholder=>"Let everyone know,What your upto?"%>
<small style="display: block; color: green; "><span id="charcount" style=" color: green; ">0</span> characters entered.   |   <span style=" color: green; " id="remaining" >140</span> characters remaining.</small>


</div>
<div class="actions"> <%= f.submit "Submit" %>
</div> 




<% end %>

app/views/shared/_search_item.html.erb
	<% if search_item.user_id!=0%>
<tr>
	<td>
<%=image_tag search_item.image_url.to_s,:id => "prof_img",:width=>50 %> </td><td>

<%= link_to search_item.name, " /profiles/#{search_item.user_id}" %></td>
</tr>
<%end%>