config/routes.rb
Devolve::Application.routes.draw do
  get "communities/create"

  get "communities/index"
  
  get "communities/delete"
  
  get "communities/join"
  get "friendship/index"
  get "communities/newpost"
  
  get "communities/newcomment"
  get "communities/destroy"
  get "communities/save"
  get "communities/show"
  get "communities/post"

  get "mailbox/show"
 get "mailbox/trash"
  get "messages/show"
get "messages/destroy"
get "messages/undelete"
get "messages/delete_from_trash"
  get "sent/index"

  get "sent/show"

  get "sent/new"
  get "sent/delete"
  
  get "sent/new_reply"
  get "messages/forward"

    resources :events
  get "search/index"

  get "codes/index"

  get "calendar/index"
get 'users/invitation'

get 'events/new'
  get "codes/create"
  get 'communities/create_post'
  get "codes/save"

  get "bookmarks/index"

  get "bookmarks/create"
  get "bookmarks/saved"
  
  get "bookmarks/notsaved"
  get "messages/reply"
 match 'mailbox/inbox' => 'mailbox#index'
 
 match 'communities/create_post'=>'communities#create_post'
  resources :microposts, :only => [:create, :destroy]
  resources :bookmarks,:only=>[:create,:destroy]
  
  resources :codes,:only=>[:create,:destroy]
  get "profiles/show"

  get "profiles/edit"
  get "microposts/destroy"
  get "bookmarks/destroy"
  
 get "home/gettingstarted"
  get "profile/show"
  match 'home/create' => 'home#create'
  match 'communities/save' => 'communities#save'
  match 'profiles/create' => 'profiles#create'
  
  match 'friendship/create' => 'friendship#create'
  
  match 'friendship/accept' => 'friendship#accept'
  
  match 'friendship/decline' => 'friendship#decline'
  
  match 'friendship/cancel' => 'friendship#cancel'

match 'microposts'=>'microposts/create'
match 'microposts/destroy'=>'microposts#destroy'

match 'bookmarks/destroy'=>'bookmarks#destroy'
match 'codes/destroy'=>'codes#destroy'
  resources :profiles,:commus,:sent,:messages,:mailbox,:member =>{ :reply => :get,:forward => :get, :undelete => :put  },:collection => { :trash => :get }
 

 get "home/getting_started_completed"
  devise_for :users
  get "home/index"
  get "home/create"
  match 'bookmarks/save' => 'bookmarks#save'
  
  match 'codes/save' => 'codes#save'
  get "home/help"

  match 'profiles/:id' => 'profile#show'
  match 'bookmarks/:id' => 'bookmarks#index'
  
  match 'communities/:id' => 'communities#show'
  
  match 'codes/:id' => 'codes#index'
    match 'codes/:id1/:id' => 'codes#view'

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user! ,:except => [:help]
  def create
    
    if params[:profile][:"birthdate(1i)"] && params[:profile][:"birthdate(2i)"] && params[:profile][:"birthdate(3i)"]
       year = params[:profile][:"birthdate(1i)"].to_i
       month = params[:profile][:"birthdate(2i)"].to_i
       day = params[:profile][:"birthdate(3i)"].to_i
       @date = "#{day}-#{month}-#{year}"
     end
    @user=User.find(current_user.id)
    @pro=Profile.new(:name=>params[:profile][:name],
    :birthdate=>@date,
    :location=>params[:profile][:location],
    :bio=>params[:profile][:bio],
    :occupation=>params[:profile][:occupation],:gender=>params[:profile][:gender],:image=>params[:profile][:image])
    
    @user.profile=@pro
    
     @user.update_attributes(:name=>params[:profile][:name])
     @user.update_attributes(:getting_started => false)
        redirect_to root_path
  end
  
  
  def feed
  Micropost.where("user_id = ?", id)
  end
  
  
  def index
     if (current_user.getting_started == true )
      @user=current_user.id
       redirect_to home_gettingstarted_path
      else 
            @user=User.find(current_user.id)
            @micropost = Micropost.new
            
            @feed_items = @user.feed.paginate(:per_page => 10,:page => params[:page])
        render :index
  end
end
  
  def help
  
  end
  


  def gettingstarted
   if current_user.getting_started == false
     redirect_to root_path
   end
    
    @profile = current_user.profile
  end
 

  def getting_started_completed
  
   
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/create.html.erb
#dummy page for action index

app/views/home/gettingstarted.html.erb
<%= content_for :extra_js do %>

<% end%>
<%= content_for :extra_css do %>

<link  href="http://fonts.googleapis.com/css?family=Rock+Salt:regular" rel="stylesheet" type="text/css" />


<%= stylesheet_link_tag 'tipBoxStyle' %>

<%= stylesheet_link_tag "gettingstarted" %>
<% end %>
<div class="wrapper">
<div id="header"><div id="logoname">Devolve</div></div>

<div id="signup">
	<h6 id="a1">Your profile </h6>
	
	<p id="finish_signup">This info will be available to whomever you connect with on Devolve.</p>
	



<%= form_for(:profile,@profile,:url =>{:action=> 'create'},:html => {:multipart => true,:method =>:put}) do |f| %>



      <br/>
  <%= f.label :Name,:id => "name_lab" %>
		   
  <%= f.text_field :name,:required=>"required",:class=>"inputValue" %>
<br/>
<br/>

  <%= f.label :BirthDate,:id=>"birthdate_lab" %>
	
  <%= f.date_select :birthdate,:prompt => true,:default => true,  :start_year => 2000, :end_year => 1930,:class=>"inputValue",:required=>"required"%>

<br/>
<br/>

  <%= f.label :Location,:id=>"location_lab" %>
	
		
  <%= f.text_field :location,:class=>"inputValue" ,:required=>"required"%>
<br/>
<br/>

  <%= f.label :Bio,:id=>"bio_lab" %>
	 <br/>
  <%= f.text_area :bio, :size => '40*10',:required=>"required"%>
		<br/>
		<br/>
	

  <%= f.label :Occupation,:id=>"occupation_lab" %>
  <%= f.text_field :occupation,:required=>"required" %>
<br/>
<br/>

 <%= f.label :Gender,:id=>"gender_lab" %> 
	<%= f.radio_button(:gender, 'male')%>
	<label id="male_lab"> Male</label>
		<%= f.radio_button(:gender, "female")%><label id="female_lab">Female</label> 
	
	<br/><br/>
		 <%= f.label :Image,:id=>"image_lab" %> 
		 
			<%= f.file_field :image %>
		<br/>
				<br/>
  <%= f.submit "Update" %>

<% end %>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/></div>

app/views/home/help.html.erb
<%= content_for :extra_css do %>

<link  href="http://fonts.googleapis.com/css?family=Rock+Salt:regular" rel="stylesheet" type="text/css" />


<%= stylesheet_link_tag "resend" %>
<% end %>
<div class="wrapper">
<div id="header"><div id="logoname">Devolve</div></div>
<div id="signup">

	<h6 id="a1">Looks like you need some help?</h6>
	
	<p id="finish_signup">Let us help you find a solution.</p>



	<h3 id="h3_help">What's the problem you are experiencing?</h3>
	<ul id="problemList">
		<li>
		 			
			  <%= link_to "Forgot your password?", new_user_password_path %><br />
			
				</li>
					<li>

		
			  <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path %><br />

				</li>
					<li>
		
			  <%= link_to "Didn't receive unlock instructions?", new_user_unlock_path %><br />
			
				</li>
		
	
  </ul>

app/views/home/index.html.erb
<%= javascript_include_tag 'profileshow' %>
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "profileshow" %>
<% end %>
<link href='http://fonts.googleapis.com/css?family=Copse' rel='stylesheet' type='text/css'>
<link  href="http://fonts.googleapis.com/css?family=Rock+Salt:regular" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Tangerine' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=MedievalSharp' rel='stylesheet' type='text/css'>
<div id="profilecontainer"><br >
<%= image_tag current_user.profile.image_url.to_s,:id=>"home_img"%>

 <h1 id="user_profile_name">
<%=current_user.profile.name%></h1>

<ul class="edit_link">
	
		<li>
		<%= image_tag "mailbox.png",:id=>"code_img"%><%= link_to "My Mail Box","/mailbox/" ,:id=>"code_link"%></li>
	
	
		<li>
		<%= image_tag "code.png",:id=>"code_img"%><%= link_to "My Code Hub","/codes/#{current_user.id}" ,:id=>"code_link"%></li>


	<li>
		<%= image_tag "bookmark.png",:id=>"bookmark_img"%><%= link_to "My Bookmarks",bookmark_url(current_user.id),:id => current_user.id %> </li>
	

	<li>

		<%= image_tag "events.png",:id=>"events_img"%><%= link_to 'View Events', calendar_index_path %></li>
	<li>

		<%= image_tag "communities.png",:id=>"communities_img"%><%= link_to "Communities",  communities_index_path %></li>
	</ul>
<br />
</div>

<div id="micropostcontainer">
	<div id="innercontainer">

<h1 class="micropost" id="micropostwhat">What's up?</h1>
<%= render 'shared/micropost_form' %>

<hr >
<br/>
<h2 id="micropostupdates"> Updates </h2>
<%= render 'shared/feed' %>
<hr />
<br />
</div>

</div>




<div id="friendscontainer" >
<div id="friendsinnerheading">	
	
<h3 id="friendsheading"> <%= pluralize(current_user.friends.count, "friend") %></h3> 
<hr id="hr_friends">


	</div>
	<div style="width:310px; height:300px; overflow:auto;">
		<%= render :partial => "friendship/friends_home" %>
		</div>
		<hr id="hr_friends1">
	</div>
	
	
	<div id="sidecontainer">

	
	<h3 id="micropost_bookmarklet">Invite your Friends to Devolve</h3> 
	
	<span id="bookmarkletinfo">
			<%= form_for :user, :as => :users, :url => invitation_path(:users) do |f| %>
		

			  <p><%= f.label :email %>:   
			  <%= f.text_field :email,:placeholder=>"Enter your friends email here."%></p>

			  <p><%= f.submit "Send an invitation" %></p>
			<% end %>
	
		
 </span>

	</div>
	
	
	
	<div id="sidecontainer1">


	<h3 id="micropost_bookmarklet">Bookmarklet for your browser</h3> 

	<span id="bookmarkletinfo">
		
		Drag this link: 
		<a href="javascript:(function(){f='http://localhost:3000/bookmarks/create?url='+encodeURIComponent(window.location.href)+'&title='+encodeURIComponent(document.title)+'&v=5&';a=function(){if(!window.open(f+'noui=1&jump=doclose','deliciousuiv5','location=yes,links=no,scrollbars=no,toolbar=no,width=900,height=550'))location.href=f+'jump=yes'};if(/Firefox/.test(navigator.userAgent)){setTimeout(a,0)}else{a()}})()">Bookmark on Devolve!</a> up to your Bookmarks Toolbar.

 </span>

	</div>
	<style>
	div.floating-menu {position:fixed;bottom:10px;background:#6b238e;border:1px solid #ffcc00;width:600px;z-index:100;-webkit-border-radius: 10px;
	  -moz-border-radius: 10px;
	  border-radius: 10px;}
	div.floating-menu a, div.floating-menu h3 {display:inline;margin:0 0.5em;}
	div.floating-menu a {color:#fff;padding:5px;}
	</style>
	<div class="floating-menu">
	<h3 style="color:#ff0">Quick Menu</h3>
	<%= link_to "Home",root_path %>
	<%= link_to "Communities",communities_index_path %>
	<%= link_to "Messages",mailbox_index_path %>
	<%= link_to "Code Hub","/codes/#{current_user.id}"%>
	<%= link_to "Bookmarks",bookmark_url(current_user.id),:id => current_user.id %> 

	</div>
	