config/routes.rb
Devolve::Application.routes.draw do
  get "communities/create"

  get "communities/index"
  
  get "communities/delete"
  
  get "communities/join"
  get "friendship/index"
  get "communities/newpost"
  
  get "communities/newcomment"
  get "communities/destroy"
  get "communities/save"
  get "communities/show"
  get "communities/post"

  get "mailbox/show"
 get "mailbox/trash"
  get "messages/show"
get "messages/destroy"
get "messages/undelete"
get "messages/delete_from_trash"
  get "sent/index"

  get "sent/show"

  get "sent/new"
  get "sent/delete"
  
  get "sent/new_reply"
  get "messages/forward"

    resources :events
  get "search/index"

  get "codes/index"

  get "calendar/index"
get 'users/invitation'

get 'events/new'
  get "codes/create"
  get 'communities/create_post'
  get "codes/save"

  get "bookmarks/index"

  get "bookmarks/create"
  get "bookmarks/saved"
  
  get "bookmarks/notsaved"
  get "messages/reply"
 match 'mailbox/inbox' => 'mailbox#index'
 
 match 'communities/create_post'=>'communities#create_post'
  resources :microposts, :only => [:create, :destroy]
  resources :bookmarks,:only=>[:create,:destroy]
  
  resources :codes,:only=>[:create,:destroy]
  get "profiles/show"

  get "profiles/edit"
  get "microposts/destroy"
  get "bookmarks/destroy"
  
 get "home/gettingstarted"
  get "profile/show"
  match 'home/create' => 'home#create'
  match 'communities/save' => 'communities#save'
  match 'profiles/create' => 'profiles#create'
  
  match 'friendship/create' => 'friendship#create'
  
  match 'friendship/accept' => 'friendship#accept'
  
  match 'friendship/decline' => 'friendship#decline'
  
  match 'friendship/cancel' => 'friendship#cancel'

match 'microposts'=>'microposts/create'
match 'microposts/destroy'=>'microposts#destroy'

match 'bookmarks/destroy'=>'bookmarks#destroy'
match 'codes/destroy'=>'codes#destroy'
  resources :profiles,:commus,:sent,:messages,:mailbox,:member =>{ :reply => :get,:forward => :get, :undelete => :put  },:collection => { :trash => :get }
 

 get "home/getting_started_completed"
  devise_for :users
  get "home/index"
  get "home/create"
  match 'bookmarks/save' => 'bookmarks#save'
  
  match 'codes/save' => 'codes#save'
  get "home/help"

  match 'profiles/:id' => 'profile#show'
  match 'bookmarks/:id' => 'bookmarks#index'
  
  match 'communities/:id' => 'communities#show'
  
  match 'codes/:id' => 'codes#index'
    match 'codes/:id1/:id' => 'codes#view'

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
    
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  
   scope :before, lambda {|end_time| {:conditions => ["ends_at < ?", Event.format_date(end_time)] }}
   scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Event.format_date(start_time)] }}

   # need to override the json view to return what full_calendar is expecting.
   # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
   def as_json(options = {})
     {
       :id => self.id,
       :title => self.title,
       :description => self.description || "",
       :start => starts_at.rfc822,
       :end => ends_at.rfc822,
       :allDay => self.all_day,
       :recurring => false,
       :url => Rails.application.routes.url_helpers.event_path(id)
     }

   end

   def self.format_date(date_time)
     Time.at(date_time.to_i).to_formatted_s(:db)
   end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
     layout 'events'
      before_filter :authenticate_user!
  
  def index   
    # full_calendar will hit the index method with query parameters
    # 'start' and 'end' in order to filter the results for the
    # appropriate month/week/day.  It should be possiblt to change
    # this to be starts_at and ends_at to match rails conventions.
    # I'll eventually do that to make the demo a little cleaner.
    
    @events = Event.scoped  
    @events = @events.after(params['start']) if (params['start'])
    @events = @events.before(params['end']) if (params['end'])
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.js  { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
      format.js { render :json => @event.to_json }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  # PUT /events/1.js
  # when we drag an event on the calendar (from day to day on the month view, or stretching
  # it on the week or day view), this method will be called to update the values.
  # viv la REST!
  def update
    @event = Event.find(params[:id])
    
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
        format.js { head :ok}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
        format.js  { render :js => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end
  

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, :id=>"title_label" %><br />
    <%= f.text_field :title %>
  </div>
<br />
  <div class="field">
    <%= f.label :starts_at, :id=>"start_label"%><br />
    <%= f.datetime_select :starts_at %>
  </div>
<br />
  <div class="field" id="start_div">
    <%= f.label :ends_at, :id=>"end_label" %><br />
    <%= f.datetime_select :ends_at %>
  </div>
<br />
  <div class="field">
	<%= f.check_box :all_day %>
    <%= f.label :all_day, :id=> "all_day_label" %>
    
  </div>
<br />
  <div class="field">
    <%= f.label :description, :id=>"description_label" %><br />
    <%= f.text_area :description %>
  </div>
<br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "eventsedit" %>
<% end %>
<div id="editevent">
<h3 id="eventheading">Editing event</h3>

<%= render 'form' %> <br />

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "eventsindex" %>
<% end %>
<div id="div_list">
<h1>Event list</h1>

<table>
  <tr>
    <th >Title</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>All day</th>
    <th>Description</th>
    <th class="displaynothing"></th>
    <th class="displaynothing"></th>
    <th class="displaynothing"></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td width="300px" align="center"><%= event.title %> </td>
    <td width="1000px" align="center"><%= event.starts_at %></td>
    <td width="1000px" align="center"><%= event.ends_at %></td>
    <td width="200px" align="center"><%= event.all_day %></td>
    <td width="300px" align="center"><%= event.description %></td>
    <td width="100px" align="center"><%= link_to 'Show', event %></td>
    <td width="100px" align="center"><%= link_to 'Edit', edit_event_path(event) %></td>
    <td width="100px" align="center"><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>

<% end %>
</table>

<br />
<%= link_to 'View calendar', calendar_index_path %> | 
<%= link_to 'New Event', new_event_path %>
</div>
<br />

app/views/events/new.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "eventsnew" %>
<% end %>
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
<div id="new_event_form">
<h3 id="eventheading">New event</h3>

<%= render 'form' %>
<br />
<%= link_to 'Back', events_path %>

</div>
<br />

app/views/events/show.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "eventsshow" %>
<% end %>
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
<div id="event_display">
	<h2> Event Information </h2>
<p id="notice"><%= notice %></p>

<p>
  <b class="label">Title : </b>
 <span class="display"> <%= @event.title %> </span>
</p>

<p>
  <b class="label">Starts at : </b>
 <span class="display">  <%= @event.starts_at %> </span>
</p>

<p>
  <b class="label">Ends at : </b>
 <span class="display"> <%= @event.ends_at %> </span>
</p>

<p>
  <b class="label">All day : </b>
 <span class="display"> <%= @event.all_day %> </span>
</p>

<p>
  <b class="label">Description : </b>
  <span class="display"> <%= @event.description %> </span>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> 
</div>