config/routes.rb
Devolve::Application.routes.draw do
  get "communities/create"

  get "communities/index"
  
  get "communities/delete"
  
  get "communities/join"
  get "friendship/index"
  get "communities/newpost"
  
  get "communities/newcomment"
  get "communities/destroy"
  get "communities/save"
  get "communities/show"
  get "communities/post"

  get "mailbox/show"
 get "mailbox/trash"
  get "messages/show"
get "messages/destroy"
get "messages/undelete"
get "messages/delete_from_trash"
  get "sent/index"

  get "sent/show"

  get "sent/new"
  get "sent/delete"
  
  get "sent/new_reply"
  get "messages/forward"

    resources :events
  get "search/index"

  get "codes/index"

  get "calendar/index"
get 'users/invitation'

get 'events/new'
  get "codes/create"
  get 'communities/create_post'
  get "codes/save"

  get "bookmarks/index"

  get "bookmarks/create"
  get "bookmarks/saved"
  
  get "bookmarks/notsaved"
  get "messages/reply"
 match 'mailbox/inbox' => 'mailbox#index'
 
 match 'communities/create_post'=>'communities#create_post'
  resources :microposts, :only => [:create, :destroy]
  resources :bookmarks,:only=>[:create,:destroy]
  
  resources :codes,:only=>[:create,:destroy]
  get "profiles/show"

  get "profiles/edit"
  get "microposts/destroy"
  get "bookmarks/destroy"
  
 get "home/gettingstarted"
  get "profile/show"
  match 'home/create' => 'home#create'
  match 'communities/save' => 'communities#save'
  match 'profiles/create' => 'profiles#create'
  
  match 'friendship/create' => 'friendship#create'
  
  match 'friendship/accept' => 'friendship#accept'
  
  match 'friendship/decline' => 'friendship#decline'
  
  match 'friendship/cancel' => 'friendship#cancel'

match 'microposts'=>'microposts/create'
match 'microposts/destroy'=>'microposts#destroy'

match 'bookmarks/destroy'=>'bookmarks#destroy'
match 'codes/destroy'=>'codes#destroy'
  resources :profiles,:commus,:sent,:messages,:mailbox,:member =>{ :reply => :get,:forward => :get, :undelete => :put  },:collection => { :trash => :get }
 

 get "home/getting_started_completed"
  devise_for :users
  get "home/index"
  get "home/create"
  match 'bookmarks/save' => 'bookmarks#save'
  
  match 'codes/save' => 'codes#save'
  get "home/help"

  match 'profiles/:id' => 'profile#show'
  match 'bookmarks/:id' => 'bookmarks#index'
  
  match 'communities/:id' => 'communities#show'
  
  match 'codes/:id' => 'codes#index'
    match 'codes/:id1/:id' => 'codes#view'

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
    
end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :content,:title,:langauge,:description
  belongs_to :user 
  validates :content, :presence => true, :length => { :maximum => 500 }
   validates :title, :presence => true 
   validates :langauge, :presence => true 
   
   default_scope :order => 'codes.created_at DESC' 

  
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
 
  before_filter :authenticate_user! ,:except => [:view]
  def index
    
         @user_current=User.find(params[:id])
         @codes = @user_current.codes.paginate(:per_page => 5,:page => params[:page])
  end

  def create
  end
  
   def save 
      
      @code = current_user.codes.build(params[:code])
       if @code.save
     render(:template=>'codes/saved')
      else
         
        render(:template=>'codes/notsaved')
      end
      end
      def view
         @user_current=User.find(params[:id1])
         @code_of=@user_current.codes.find(params[:id])
      end
      
        def destroy
      @code=Code.find(params[:id])
          @code.destroy

           redirect_to  profile_path(current_user.id)
        end

end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_code.html.erb
<tr> <td class="micropost">

Code Title : <%= link_to code.title,"/codes/#{@user_current.id}/#{code.id}" %><br />
Programming language : <%=code.langauge%> <br />
Share your code : <%= link_to root_url+"codes/#{@user_current.id}/#{code.id}",root_url+"codes/#{@user_current.id}/#{code.id}"%>
<span id="deletelink"><%= link_to "delete",code_url(code.id),:id => code.id,:method=>:delete,:confirm => "You sure?"%> </span> <br /> 
<hr />
</tr>
</td>

 

app/views/codes/create.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "codehubcreate" %>

<%= stylesheet_link_tag "syntax" %>
<% end %>
<link href='http://fonts.googleapis.com/css?family=Copse' rel='stylesheet' type='text/css'>
<link  href="http://fonts.googleapis.com/css?family=Rock+Salt:regular" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>

<div id="codehubform">
	<h3 id="codehubheading"> Add a code block to your code hub, and start sharing </h3>
	<br />
	<%= form_for :code,:url =>{:controller=>'codes',:action=> 'save'} do |f| %>
		<%= render 'shared/error_messages', :object => f.object %>
	 <div class="field" id="codehubinnerform">

		<%= f.label :Title, :id => "code_title_label"%>
		<%= f.text_field :title %>
		<br/>
		<br/>
		<%=f.label :langauge, :id=>"code_langauge_label"%>
		<%= f.text_field :langauge%>
			<br/>
			<br/>
			<%= f.label :Code_description, :id=>"code_description_label"%>
		<%= f.text_area :description %> 
		<%= f.label :Enter_your_code_here, :id=>"code_content_label"%>
	<%= f.text_area :content,:value=>'<code lang="Enter_your_language_here"> 
	
	   Enter your code here....  
	
	</code>' %> </div>

	<div class="actions"> <%= f.submit "Submit" %>
		<input type="button" value="Cancel" onclick="window.close()" id="code_cancel"/>
	</div> <% end %>

	
	</div>


	</div>
	<style>
	div.floating-menu {position:fixed;bottom:10px;background:#6b238e;border:1px solid #ffcc00;width:600px;z-index:100;-webkit-border-radius: 10px;
	  -moz-border-radius: 10px;
	  border-radius: 10px;}
	div.floating-menu a, div.floating-menu h3 {display:inline;margin:0 0.5em;}
	div.floating-menu a {color:#fff;padding:5px;}
	</style>
	<div class="floating-menu">
	<h3 style="color:#ff0">Quick Menu</h3>
	<%= link_to "Home",root_path %>
	<%= link_to "Communities",communities_index_path %>
	<%= link_to "Messages",mailbox_index_path %>
	<%= link_to "Code Hub","/codes/#{current_user.id}"%>
	<%= link_to "Bookmarks",bookmark_url(current_user.id),:id => current_user.id %> 

	</div>
	

app/views/codes/index.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "codehubindex" %>

<%= stylesheet_link_tag "syntax" %>
<% end %>
<link href='http://fonts.googleapis.com/css?family=Copse' rel='stylesheet' type='text/css'>
<link  href="http://fonts.googleapis.com/css?family=Rock+Salt:regular" rel="stylesheet" type="text/css" />



			
			<%@logged_in_user=User.find(current_user.id)%>
			<div id="codehubbody">


	<h3 id="codehubheading">	<%=@user_current.profile.name%>'s Code blocks </h3>
					<strong>Total number of code blocks saved: </strong> <%= @user_current.codes.count %>
<br /> 
				
				<% if @user_current == @logged_in_user  %>
					<%= link_to "Create a new code block","javascript:(function(){f='"+root_url+"codes/create?&v=5&';a=function(){if(!window.open(f+'noui=1&jump=doclose','deliciousuiv5','location=yes,links=no,toolbar=no,scrollbars=yes,width=900'))location.href=f+'jump=yes'};if(/Firefox/.test(navigator.userAgent)){setTimeout(a,0)}else{a()}})()", :id => "link_new_code"%><%end%>
					<br/><br />
					

						<% if friend_link( @user_current,@logged_in_user) == '3' || @user_current == @logged_in_user  %>
						<% if @user_current.codes.empty? %>
						<p id="notsavedmsg">The user has not yet saved any codes!. </p>
						<%else%>
						<table class="bookmarks" summary="User bookmarks" width="100%">
							 <%= render @codes %>
						</table>
					<span id="paginateview">	<%= will_paginate @codes %> </span>
						 <% end %>
						<%else%>
						Only friends can access <%= @user_current.profile.name%>'s code blocks
			<%end%>
			
			</div>
			<style>
			div.floating-menu {position:fixed;bottom:10px;background:#6b238e;border:1px solid #ffcc00;width:600px;z-index:100;-webkit-border-radius: 10px;
			  -moz-border-radius: 10px;
			  border-radius: 10px;}
			div.floating-menu a, div.floating-menu h3 {display:inline;margin:0 0.5em;}
			div.floating-menu a {color:#fff;padding:5px;}
			</style>
			<div class="floating-menu">
			<h3 style="color:#ff0">Quick Menu</h3>
			<%= link_to "Home",root_path %>
			<%= link_to "Communities",communities_index_path %>
			<%= link_to "Messages",mailbox_index_path %>
			<%= link_to "Code Hub","/codes/#{current_user.id}"%>
			<%= link_to "Bookmarks",bookmark_url(current_user.id),:id => current_user.id %> 

			</div>

		

app/views/codes/notsaved.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "codehubnotsaved" %>
<% end %>
<link href='http://fonts.googleapis.com/css?family=Copse' rel='stylesheet' type='text/css'>
<link  href="http://fonts.googleapis.com/css?family=Rock+Salt:regular" rel="stylesheet" type="text/css" />

<div id="codehubnotsaved">
<h1 id="codehubnotsavedheading">Code block not saved! (there were some errors)</h1>
<input type="button" value="Go Back" onClick="history.go(-1);return true;" id="back_button"/>
<input type="button" value="Close Window" onclick="window.close()" id="close_button"/>
</div>

app/views/codes/saved.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "codehubsave" %>
<% end %>
<link href='http://fonts.googleapis.com/css?family=Copse' rel='stylesheet' type='text/css'>
<link  href="http://fonts.googleapis.com/css?family=Rock+Salt:regular" rel="stylesheet" type="text/css" />

<div id="codehubsaved">
<h1 id="codehubsavedheading">Code block saved!</h1>
<input type="button" value="Close Window" onclick="window.close()" id="submit_button" />

<input type="button" value="Go Back" onClick="history.go(-1);return true;" id="back_button" />
</div>

app/views/codes/view.html.erb
<%= content_for :extra_css do %>
<%= stylesheet_link_tag "codehubview" %>

<%= stylesheet_link_tag "syntax" %>
<% end %>
<link href='http://fonts.googleapis.com/css?family=Copse' rel='stylesheet' type='text/css'>
<link  href="http://fonts.googleapis.com/css?family=Rock+Salt:regular" rel="stylesheet" type="text/css" />
<div id="codehubviewcontent">
<p> <span> Code title : </span><span><%=@code_of.title%></span> <br/>
<span>Written by </span> <span> <%=@user_current.profile.name%></span> <br />
<span>Language: <%=@code_of.langauge%></span> </p>


<h3>Description</h3>
<%=@code_of.description%>



<h3>CODE</h3><p>
<%=  coderay(@code_of.content)%></p>



Share using link: <%= link_to root_url+"codes/#{@user_current.id}/#{@code_of.id}",root_url+"codes/#{@user_current.id}/#{@code_of.id}"%>

<%= link_to "delete",code_url(@code_of.id),:id => @code_of.id,:method=>:delete,:confirm => "You sure?" %>
</div>

<style>
div.floating-menu {position:fixed;bottom:10px;background:#6b238e;border:1px solid #ffcc00;width:600px;z-index:100;-webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  border-radius: 10px;}
div.floating-menu a, div.floating-menu h3 {display:inline;margin:0 0.5em;}
div.floating-menu a {color:#fff;padding:5px;}
</style>
<div class="floating-menu">
<h3 style="color:#ff0">Quick Menu</h3>
<%= link_to "Home",root_path %>
<%= link_to "Communities",communities_index_path %>
<%= link_to "Messages",mailbox_index_path %>
<%= link_to "Code Hub","/codes/#{current_user.id}"%>
<%= link_to "Bookmarks",bookmark_url(current_user.id),:id => current_user.id %> 

</div>